# Generated by Django 5.0 on 2023-12-13 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('datacontrato', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('senha', models.CharField(max_length=20)),
                ('codigo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clinica.pessoa')),
            ],
        ),
    ]
