# Generated by Django 5.0 on 2023-12-13 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('especialidade', models.CharField(max_length=40)),
                ('crm', models.IntegerField()),
                ('codigo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clinica.funcionario')),
            ],
        ),
    ]
