# Generated by Django 5.0 on 2023-12-13 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_medico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('codigo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clinica.medico')),
                ('data_agenda', models.DateField()),
                ('horario', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
                ('telefone', models.CharField(max_length=70)),
                ('codigomedico', models.IntegerField()),
            ],
        ),
    ]
