# Generated by Django 5.0 on 2023-12-13 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProntuarioEletronico',
            fields=[
                ('anamnese', models.CharField(max_length=1000)),
                ('medicamentos', models.CharField(max_length=100)),
                ('atestados', models.CharField(max_length=300)),
                ('exames', models.CharField(max_length=300)),
                ('codigo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clinica.paciente')),
            ],
        ),
    ]
