# Generated by Django 5.0 on 2023-12-13 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0009_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PessoaPaciente',
        ),
    ]
